workflows:
  build-foran:
    name: Build Foran APK
    instance_type: mac_mini
    max_build_duration: 10
    environment:
      vars:
        PACKAGE_NAME: "com.foran.app"
      node: "lts/*"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap add android
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
