workflows:
  build-foran:
    name: Build Foran APK
    instance_type: linux_x2
    max_build_duration: 10
    environment:
      vars:
        PACKAGE_NAME: "com.foran.app"
      node: "lts/*"
    scripts:
      - name: Prepare project
        script: |
          npm install
          npx cap init foran com.foran.app --web-dir=www --npm-client=npm
          npx cap add android
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
